const { app, input } = require('@azure/functions');

// Define the SignalR input binding to automatically fetch token details
const signalRInput = input.generic({
    type: 'signalRConnectionInfo',
    hubName: 'resumeHub', // You can name your hub anything you like!
    name: 'connectionInfo'
});

app.post('negotiate', {
    authLevel: 'anonymous',
    extraInputs: [signalRInput],
    handler: async (request, context) => {
        // Retrieve the token details generated by Azure SignalR
        const connectionInfo = context.extraInputs.get(signalRInput);
        
        return {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(connectionInfo)
        };
    }
});
